package pkg21kb1a0574.atm;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.sql.PreparedStatement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author admin
 */
public class INSERT extends javax.swing.JFrame {

    /**
     * Creates new form INSERT
     */
    public INSERT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INSERT");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("USERNAME");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("MOBILE NO");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("INITIAL BALANCE");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton3.setText("INSERT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg21kb1a0574/atm/wrong.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new ADMINISTRATOR_MAIN().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField4.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
            if (jTextField1.getText().equals(""))	
                {
                    javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                } 
            else if (jTextField2.getText().equals("")) 
                {
                    javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                }
            else if (jTextField4.getText().equals("")) 
                {
                    javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                }
            else
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "system");
                String Query="SELECT ACCOUNTNO FROM PREETHI.ACCOUNTS WHERE USERNAME=?";
                PreparedStatement ps=con.prepareStatement(Query);
                ps.setString(1,"DEFAULT");
                ResultSet rs= ps.executeQuery();
                if(rs.next())
                {
                  long acc=Long.parseLong(rs.getString("ACCOUNTNO"));
                  long acc1=acc+1;
                  double bal=Double.parseDouble(jTextField4.getText());
                  String q1="DELETE FROM PREETHI.ACCOUNTS WHERE ACCOUNTNO=?";
                  PreparedStatement pstmt=con.prepareStatement(q1);
                  pstmt.setLong(1,Long.parseLong(rs.getString("ACCOUNTNO")));
                  pstmt.executeUpdate();
                  String Query1="INSERT INTO PREETHI.ACCOUNTS(ACCOUNTNO,USERNAME,MOBILENO) VALUES(?,?,?)";
                  String Query2="INSERT INTO PREETHI.BALANCE VALUES(?,?)";
                  String Query3="INSERT INTO PREETHI.ACCOUNTS(ACCOUNTNO,USERNAME) VALUES(?,?)";
                  java.sql.PreparedStatement ps1=con.prepareStatement(Query1);
                  ps1.setLong(1,Long.parseLong(rs.getString("ACCOUNTNO")));
                  ps1.setString(2,jTextField1.getText());
                  ps1.setLong(3,Long.parseLong(jTextField2.getText()));
                  java.sql.PreparedStatement ps2=con.prepareStatement(Query2);
                  ps2.setLong(1,Long.parseLong(rs.getString("ACCOUNTNO")));
                  ps2.setDouble(2,Double.parseDouble(jTextField4.getText()));
                  java.sql.PreparedStatement ps3=con.prepareStatement(Query3);
                  ps3.setLong(1,acc1);
                  ps3.setString(2,"DEFAULT");
                  if(jTextField1.getText().equals(""))
                  {
                      javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                  }
                  else if (jTextField2.getText().equals("")) 
                  {
                      javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                  }
                  else if (jTextField4.getText().equals("")) 
                  {
                      javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                  }
                  else if(bal<500)
                  {
                      javax.swing.JOptionPane.showMessageDialog(null, "INTIAL BALANCE SHOULD BE MINIMUM 500Rs.");
                  }
                  else
                  {
                      ps1.executeUpdate();
                      ps2.executeUpdate();
                      ps3.executeUpdate();
                      new INSERT_FINAL().setVisible(true);
                      dispose();
                  }
                }
                else
                {
                  javax.swing.JOptionPane.showMessageDialog(null, "ACCOUNT  CAN'T BE CREATED");  
                }
            }
              
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       new WELCOME_TO_CSE_BANK().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            jTextField2.requestFocus();
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            jTextField4.requestFocus();
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            try
        {
            if (jTextField1.getText().equals(""))	
                {
                    javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                } 
            else if (jTextField2.getText().equals("")) 
                {
                    javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                }
            else if (jTextField4.getText().equals("")) 
                {
                    javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                }
            else 
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "system");
                String Query="SELECT ACCOUNTNO FROM PREETHI.ACCOUNTS WHERE USERNAME=?";
                PreparedStatement ps=con.prepareStatement(Query);
                ps.setString(1,"DEFAULT");
                ResultSet rs= ps.executeQuery();
                if(rs.next())
                {
                  long acc=Long.parseLong(rs.getString("ACCOUNTNO"));
                  long acc1=acc+1;
                  double bal=Double.parseDouble(jTextField4.getText());
                  String q1="DELETE FROM PREETHI.ACCOUNTS WHERE ACCOUNTNO=?";
                  PreparedStatement pstmt=con.prepareStatement(q1);
                  pstmt.setLong(1,Long.parseLong(rs.getString("ACCOUNTNO")));
                  pstmt.executeUpdate();
                  String Query1="INSERT INTO PREETHI.ACCOUNTS(ACCOUNTNO,USERNAME,MOBILENO) VALUES(?,?,?)";
                  String Query2="INSERT INTO PREETHI.BALANCE VALUES(?,?)";
                  String Query3="INSERT INTO PREETHI.ACCOUNTS(ACCOUNTNO,USERNAME) VALUES(?,?)";
                  java.sql.PreparedStatement ps1=con.prepareStatement(Query1);
                  ps1.setLong(1,Long.parseLong(rs.getString("ACCOUNTNO")));
                  ps1.setString(2,jTextField1.getText());
                  ps1.setLong(3,Long.parseLong(jTextField2.getText()));
                  java.sql.PreparedStatement ps2=con.prepareStatement(Query2);
                  ps2.setLong(1,Long.parseLong(rs.getString("ACCOUNTNO")));
                  ps2.setDouble(2,Double.parseDouble(jTextField4.getText()));
                  java.sql.PreparedStatement ps3=con.prepareStatement(Query3);
                  ps3.setLong(1,acc1);
                  ps3.setString(2,"DEFAULT");
                  if(jTextField1.getText().equals(""))
                  {
                      javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                  }
                  else if (jTextField2.getText().equals("")) 
                  {
                      javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                  }
                  else if (jTextField4.getText().equals("")) 
                  {
                      javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                  }
                  else if(bal<500)
                  {
                      javax.swing.JOptionPane.showMessageDialog(null, "INTIAL BALANCE SHOULD BE MINIMUM 500Rs.");
                  }
                  else
                  {
                      ps1.executeUpdate();
                      ps2.executeUpdate();
                      ps3.executeUpdate();
                      new INSERT_FINAL().setVisible(true);
                      dispose();
                  }
                }
                else
                {
                  javax.swing.JOptionPane.showMessageDialog(null, "ACCOUNT  CAN'T BE CREATED");  
                }
            }
              
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INSERT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
